# Site settings
title: Pseudo Surfer
email: justin@pseudosurfer.com
description: >
  A portfolio site for my photography and other musings
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://127.0.0.1:4000' # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: PseudoSurfer

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-inline-svg
  - jekyll-gallery-generator

svg:
  optimize: true

collections:
    creators:
      output: true
    photos:
      output: true


defaults:
  - scope:
      path: ""
      type: "creators"
    values:
      layout: "creator"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exiftag:
 sources:
   - photos/"Ado"
   - photos/"Balbo Park"

galleries:
  Ado:
    best_image: "150507AdoElephantPark006.jpg"
    info:
        desc: "Ado Elephant Park, Eartern Cape, South Africa" # Info fields can be used in custom templates.
  Balbo Park:
    best_image: "140811_BalboaPark_013.JPG"
    info:
        desc: "Balboa Park, San Diego, California" # Info fields can be used in custom templates.
